name: application
server:
  port: 6002
  servlet:
    context-path: /mark    #请求地址前加上mark,比如http://127.0.0.1/springbootconfigdemo/mark/controler地址
spring:
  profiles:
    active: dev

---
name: dev-initinfo
spring:
  profiles: dev

---
name: prod-initinfo
spring:
  profiles: prod